//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaPacifica.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class PacificaContext : DbContext
    {
        public PacificaContext()
            : base("name=PacificaContext")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
       
            public virtual DbSet<Departamento> Departamento { get; set; }
            public virtual DbSet<Distrito> Distrito { get; set; }
            public virtual DbSet<Provincia> Provincia { get; set; }
     
       
    }
 
}
