//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pruebaPacifica.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string documento { get; set; }
        public string email { get; set; }
        public System.DateTime nacimiento { get; set; }
        public string celular { get; set; }
        public Nullable<int> distrito_id { get; set; }
        public string motivo { get; set; }
        public string mensaje { get; set; }
    }
}
